# Arquivo de configurações da aplicação

# --SMTP--
# Configurações do servidor SMTP
smtp.host="smtp.gmail.com"
smtp.port=587
smtp.username="sua.conta@gmail.com"
smtp.password="aaaa aaaa aaaa aaaa"

# --Templates--
# Pasta de modelos de email
templates.folderPath=C:\Users\Administrator\Documents\mailTemplates

# --SQL--
# Configurações relativas ao banco de dados
sql.url=jdbc:postgresql:DeereMail
sql.user=postgres
sql.password=1234

# --Hash--
# Configurações relativas à geração de hash para senhas de usuário
# Não precisa de nenhuma alteração para funcionar. Se não tiver certeza do que está fazendo, NÃO ALTERE
hash.iterationCount=65536
hash.keySize=128
hash.saltLength=16
