#define qual perfil está sendo utilizado (dev ou test)
spring.profiles.active=dev

#configurações comums de toda aplicação
spring.application.name=mailscheduler
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

#configurações específicas da biblioteca quartz (envios agendados)
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=MailScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.threadPool.threadCount=5

#configurações relativas à persistência das funções do quartz em banco de dados
spring.quartz.properties.org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=false
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.jdbc.schema=classpath:org/quartz/impl/jdbcjobstore/tables_postgres.sql

