# Propriedades extras para uso com Supabase (perfil "cloud")
# Ativado com: ./mvnw spring-boot:run -Dspring.profiles.active=cloud

supabase.project-url=${supabase.projectUrl}
supabase.service-role-key=${supabase.serviceRoleKey}
