#configurações do banco postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/DeereMail
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#${DB_USER} e ${DB_PASSWORD} são as variáveis de ambiente do projeto, no caso do linux elas são configuradas no arquivo .bashrc ou .zshrc 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true