spring.application.name=mailscheduler

# Datasource — valores lidos do settings.ini via @PropertySource
spring.datasource.url=${sql.url}
spring.datasource.username=${sql.user}
spring.datasource.password=${sql.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
